version: '3'

services:
    php-fpm:
        image: jkaninda/laravel-php-fpm
        container_name: php-fpm
        working_dir: /var/www
        volumes:
            #Project root
            - ./:/var/www/
            - ~/.ssh:/root/.ssh
        networks:
            - sail

    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - "81:80"
        volumes:
            - ./nginx.default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/
        environment:
            - DOCUMENT_ROOT=/var/www
            - CLIENT_MAX_BODY_SIZE=20M
            - LARAVEL_PROCS_NUMBER=2
        depends_on:
            - php-fpm
        networks:
            - sail

    mysql:
        image: 'mysql:8.0'
        container_name: logistic-mysql
        ports:
            - "3307:3306"
        volumes:
            - .data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=app
            - MYSQL_USER=app
            - MYSQL_PASSWORD=secret
        networks:
            - sail

    redis:
        image: 'redis:alpine'
        container_name: logistic-redis
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - .data/redis:/data
        networks:
            - sail
networks:
    sail:
        driver: bridge
        external: true
